version: '3.8'

services:
  telegram-xspf-bot:
    build: .
    container_name: telegram-xspf-bot
    restart: always
    environment:
      # Telegram Bot Configuration
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}

      # Google Service Account Credentials
      - GOOGLE_CREDENTIALS_TYPE=service_account
      - GOOGLE_CREDENTIALS_PROJECT_ID=${GOOGLE_CREDENTIALS_PROJECT_ID}
      - GOOGLE_CREDENTIALS_PRIVATE_KEY_ID=${GOOGLE_CREDENTIALS_PRIVATE_KEY_ID}
      - GOOGLE_CREDENTIALS_PRIVATE_KEY=${GOOGLE_CREDENTIALS_PRIVATE_KEY}
      - GOOGLE_CREDENTIALS_CLIENT_EMAIL=${GOOGLE_CREDENTIALS_CLIENT_EMAIL}
      - GOOGLE_CREDENTIALS_CLIENT_ID=${GOOGLE_CREDENTIALS_CLIENT_ID}
      - GOOGLE_CREDENTIALS_AUTH_URI=${GOOGLE_CREDENTIALS_AUTH_URI}
      - GOOGLE_CREDENTIALS_TOKEN_URI=${GOOGLE_CREDENTIALS_TOKEN_URI}
      - GOOGLE_CREDENTIALS_AUTH_PROVIDER_CERT_URL=${GOOGLE_CREDENTIALS_AUTH_PROVIDER_CERT_URL}
      - GOOGLE_CREDENTIALS_CLIENT_CERT_URL=${GOOGLE_CREDENTIALS_CLIENT_CERT_URL}